### ISSUE TITLE
Complete Noob issues line 368 on ./generate-world

### ISSUE THREAD

**Issue by fakebob** [cgutteridge/geocraft#31]
https://github.com/cgutteridge/geocraft/blob/d0442ed2e0cca7f73f95d4e19fc1ff3fdf80d8f6/generate-world#L355
Edited - ran the latest code, and came up with line 355, not 368. Same error though.
Hi Guys.

I am a complete Noob when it comes to running stuff on an ubuntu virtual terminal on windows - i preciously ran this no problems on my macbook pro, but it died.

I'm getting a constant error on line 318 and I have no idea how to fix it. Any clues? I have the necessary Archive::Zip and imagemagick installed but no clue on this one.

Here's the error message:
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "<html>\r\n<head><tit...") at ./generate-world line 355.

Now, I did notice that the O/S have changed their file structure from /docs/ to /datasets/, so I changed that in the .generate-world script/file accordingly and came up with another error, but with a lot less 'junk' above it.

Any ideas?

**Comment by fakebob** [comment]
OK, I managed to get the thing working using eastings and northings in the command line, and although it threw up a few errors in the permissions (cp) it's now settled down to parsing through the data and creating chunks. -- edit -- its literally just cache'ing a single chunk over and over.

There's still that error when I use the postcode option though. If anyone has any ideas, I'd appreciate the feedback - I get these things stuck in my head and then I can't sleep!

**Comment by fakebob** [comment]
An  update! The world generates, but it's completely flat and only has a few buildings on it. When I did my previous one (which was deleted from my server somehow) it had buildings with height and terrain. This just looks like MC has interpreted the materials and made a flat map. This is the command i'm using to generate it:

./generate-world --centre 249954,56708 --size 5000 Plymouth --replace

Am I doing something wrong? I've started learning perl, just in case, but can't see where I'm missing the DSM data.

**Comment by RobinWhitfield** [comment]
Regarding the lack of height data, see #22

The last time I had a good look at this project, my thoughts (and the author's comments in the aforementioned issue kind of reflect mine) were that for how much has changed, in order for it to function properly again it needs quite a bit rewriting. It's a few years on from that now which means it's slowly getting less and less likely to be able to bodged to make it work.

The LiDAR data seems to have had a format change, the way the OSM tiles are downloaded en-masse is against OSM's Ts&Cs, the way the OSM tiles are processed creates random gaps and features due to visual items on the mapping, block data is using legacy IDs (and therefore also has very limited support for current blocks), world data is in a very outdated format and has to be upgraded to be used etc.

I've not really done much with Minecraft for some years and I'm also not much of a developer, otherwise I'd love to take this project on.

The new Minecraft block and world format is pretty well documented, OSM data can be turned into all sorts of different formats and extracted in a variety of ways (https://wiki.openstreetmap.org/wiki/Frameworks#Webmaps), and the LiDAR data likely has some documentation around the new format somewhere...

**Comment by fakebob** [comment]
Hmmm. I thought as much. I'm going to knuckle down to some learning and see what I can do. There's nothing quite like jumping  into the deep end to get you learning quickly. 

Maybe a complete rewrite may be the only way to go. I will have a good nose through the documentation and see if i can come up with a plan.

Thanks for your input though. Gives me a direction to start from!

**Comment by RobinWhitfield** [comment]
Yeah I'd start by taking a look at the LiDAR data being brought in and see whether the data it's trying to get seems to be in a different format and then go from there.

I managed to get a useable map back in the day by utilising older mapping data.
